In [1]:
import cv2

import numpy as np


In [2]:
print(cv2.__version__)


3.1.0


In [3]:
import cv2, numpy
contour = numpy.array( [ 
(378, 949), (375, 940), (368, 934), 
(359, 932), (350, 937), (345, 955), 
(351, 962), (359, 966), (368, 964), 
(376, 958) ], numpy.float32 )
cv2.isContourConvex(contour)
print ('contours')
print (contour)

contours
[[378. 949.]
 [375. 940.]
 [368. 934.]
 [359. 932.]
 [350. 937.]
 [345. 955.]
 [351. 962.]
 [359. 966.]
 [368. 964.]
 [376. 958.]]


In [4]:
from __future__ import print_function

import cv2
import numpy as np
  
img = cv2.imread('/Users/anirudh/Desktop/ss.png')  #'0' to read color as gray scale 
img = cv2.resize(img, (0,0), fx=1, fy=1)

img_blr0 = cv2.GaussianBlur(img, (3, 3), 2, 3) #5 by 5 kernel, sigma 3 for x and y
img_blr1 = cv2.GaussianBlur(img, (5, 5), 3, 3) #5 by 5 kernel, sigma 3 for x and y
img_blr2 = cv2.GaussianBlur(img, (7, 7), 3, 7) 
img_blr3 = cv2.GaussianBlur(img, (19, 19), 23, 31)
img_blr4 = cv2.GaussianBlur(img, (21,21), 36, 47)

#cv2.namedWindow('gaussian1',0)
#cv2.resizeWindow('gaussian1',256,256)
cv2.imshow('gaussian1',img_blr1)
cv2.imshow('gaussian2',img_blr2)
cv2.imshow('gaussian3',img_blr3)
cv2.imshow('gaussian4',img_blr4) 

#img_diff 
img_diff1 = img - img_blr1 
img_diff2 = img - img_blr2 
img_diff3 = img - img_blr3
img_diff4 = img - img_blr4

cv2.imshow('diff1', img_diff1) 
cv2.imshow('diff2', img_diff2)
cv2.imshow('diff3', img_diff3)
cv2.imshow('diff4', img_diff4)

#img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow('gray image', img_gray)

In [5]:
ret,thresh = cv2.threshold(img_gray,200,255,0) #threshold=220
cv2.imshow('thresholded binary',thresh)

In [6]:
_,contours,hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
contours = [cv2.approxPolyDP(cnt, 3, True) for cnt in contours]
print ('contours')
#print (contours) 

epsilon = 0.001*cv2.arcLength(contours[0],True) 
approx = cv2.approxPolyDP(contours[0],epsilon,True) 

contours


In [7]:
#hull = cv2.convexHull(cnt)
cv2.drawContours(img, contours, -1, (128,255,255),3) #draw contours on original image
#1st argument: source image
#2nd argument: contours as a Python list
#3rd argument: index of contours for individual contour. 
#4-5-6:        color,
#7th argument: thickness.

#cv2.drawContours(img, hull, -1, (0,0,255),3)
cv2.imshow('findContours',img) 



In [ ]:

#ellipse = cv2.fitEllipse(cnt)
#cv2.ellipse('EllipsCountours',img) 

mask = np.zeros(thresh.shape,np.uint8)
cv2.drawContours(mask,contours[0],0,255,-1)
pixelpoints = np.transpose(np.nonzero(mask))
print ('[cnt]')
print("number of contours =", len(contours))
print ("background =", contours[0])

cnt = contours[1]
M = cv2.moments(cnt)
print (M)

x,y,w,h = cv2.boundingRect(contours[1])
cv2.rectangle(img, (x,y), (x+w, y+h), (0,0,255), 2)



cv2.imshow("brect", img)

#minized rectangle
Rect = cv2.minAreaRect(cnt)
box = cv2.boxPoints(Rect)
box = np.int0(box)
cv2.drawContours(img, [box], 0, (0,255,0), 2)

cv2.imshow("mArect", img)

#circle
(x,y),radius = cv2.minEnclosingCircle(cnt)
center = (int(x),int(y))
radius = int(radius)
cv2.circle(img,center,radius,(0,255,0),2)

ellipse = cv2.fitEllipse(cnt)
cv2.ellipse(img,ellipse,(0,255,0),2)

cv2.imshow("circle", img)

#fit line
rows,cols = img.shape[:2]
[vx,vy,x,y] = cv2.fitLine(cnt, cv2.DIST_L2,0,0.01,0.01)
lefty = int((-x*vy/vx) + y)
righty = int(((cols-x)*vy/vx)+y)
cv2.line(img,(cols-1,righty),(0,lefty),(0,255,0),2)

cv2.imshow("line", img)

#contour on the masked image
mask = np.zeros(img_gray.shape,np.uint8)
cv2.drawContours(mask,[cnt],0,255, -1)
print("\ncontours object", [cnt])

#pixel points in a contour
pixelpoints1 = np.transpose(np.nonzero(mask))
print ('\npixelpoints  mask') 
print (pixelpoints1)

cv2.imshow("mask1", mask)


min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(img_gray,mask = mask)
print("\nminMaxValLoc")
print("minVal =",min_val)
print("maxVal =", max_val)
print("MinLocation =", min_loc)
print("minLocation =", max_loc)

mean_val = cv2.mean(img,mask = mask)

print("\nmean =", mean_val)

cv2.circle(img_gray, min_loc, 5, (0,122,0), 2)
cv2.circle(img_gray, max_loc, 5, (0,255,0), 2)
cv2.imshow("min_loc_max_loc_ImgGray", img_gray)

cv2.waitKey(0)
cv2.destroyAllWindows()

[cnt]
number of contours = 2
background = [[[  1   1]]

 [[  1 533]]

 [[533 533]]

 [[533   1]]]
{'m30': 495164493004.4, 'nu02': 0.1271540087319533, 'm10': 6323073.333333333, 'nu03': -0.020351231777656756, 'm02': 1956632878.6666665, 'nu21': -0.005974825524097533, 'm00': 24120.0, 'm20': 1737951860.6666665, 'm03': 586141899067.0, 'm01': 6738672.666666666, 'mu20': 80354166.6902523, 'mu02': 73974947.13762689, 'm12': 494037617711.3333, 'nu11': -0.06243860863799846, 'm11': 1730222139.3333333, 'mu11': -36325184.07720637, 'nu20': 0.1381191174624602, 'mu12': 1402206097.9410172, 'mu30': -2570483862.9780884, 'mu03': -1838797730.7303467, 'nu30': -0.028449302499093096, 'm21': 465965756651.06665, 'mu21': -539844257.843998, 'nu12': 0.015519173654791782}

contours object [array([[[312, 113]],

       [[364, 270]],

       [[214, 420]],

       [[229, 367]],

       [[ 96, 270]],

       [[260, 269]]], dtype=int32)]

pixelpoints  mask
[[113 312]
 [114 312]
 [115 311]
 ...
 [419 214]
 [419 215]
 [420 2