In [1]:

import cv2
import numpy as np

img = cv2.imread('/Users/anirudh/Desktop/1trak.jpg')  #'0' to read color as gray scale \
img = cv2.resize(img, (0,0), fx=1, fy=1)

img_blr0 = cv2.GaussianBlur(img, (3, 3), 2, 3) #5 by 5 kernel, sigma 3 for x and y\
img_blr1 = cv2.GaussianBlur(img, (5, 5), 3, 3) #5 by 5 kernel, sigma 3 for x and y\
img_blr2 = cv2.GaussianBlur(img, (7, 7), 3, 7) 
img_blr3 = cv2.GaussianBlur(img, (19, 19), 23, 31)
img_blr4 = cv2.GaussianBlur(img, (21,21), 36, 47)

#cv2.namedWindow('gaussian1',0)\
#cv2.resizeWindow('gaussian1',256,256)\
cv2.imshow('gaussian1',img_blr1)
cv2.imshow('gaussian2',img_blr2)
cv2.imshow('gaussian3',img_blr3)
cv2.imshow('gaussian4',img_blr4) 

#img_diff \
img_diff1 = img - img_blr1 
img_diff2 = img - img_blr2 
img_diff3 = img - img_blr3
img_diff4 = img - img_blr4

cv2.imshow('diff1', img_diff1) 
cv2.imshow('diff2', img_diff2)
cv2.imshow('diff3', img_diff3)
cv2.imshow('diff4', img_diff4)

#img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow('gray image', img_gray)

ret,thresh = cv2.threshold(img_gray,200,255,0) #threshold=220
cv2.imshow('thresholded binary',thresh)

_,contours,hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
contours = [cv2.approxPolyDP(cnt, 3, True) for cnt in contours]
print ('contours')
#print (contours)

epsilon = 0.001*cv2.arcLength(contours[0],True) 
approx = cv2.approxPolyDP(contours[0],epsilon,True) 

#hull = cv2.convexHull(cnt)
cv2.drawContours(img, contours, -1, (128,255,255),3) #draw contours on original image\
#1st argument: source image
#2nd argument: contours as a Python list\
#3rd argument: index of contours for individual contour. \
#4-5-6:        color,\
#7th argument: thickness.\

#cv2.drawContours(img, hull, -1, (0,0,255),3)\
cv2.imshow('findContours',img) 


# new code addition\


#ellipse = cv2.fitEllipse(cnt)\
#cv2.ellipse('EllipsCountours',img) \

mask = np.zeros(thresh.shape,np.uint8)

for cnt in contours:
    cv2.drawContours(mask,cnt,0,255,-1)
    pixelpoints = np.transpose(np.nonzero(mask))
    print ('[cnt]')
    print("number of contours =", len(contours))
    print ("background =", cnt)

    M = cv2.moments(cnt)
    print (M)

    x,y,w,h = cv2.boundingRect(cnt)
    cv2.rectangle(img, (x,y), (x+w, y+h), (0,0,255), 2)

    #minized rectangle\
    Rect = cv2.minAreaRect(cnt)
    box = cv2.boxPoints(Rect)
    box = np.int0(box)
    cv2.drawContours(img, [box], 0, (0,255,0), 2)

    #circle\
    (x,y),radius = cv2.minEnclosingCircle(cnt)
    center = (int(x),int(y))
    radius = int(radius)
    cv2.circle(img,center,radius,(0,255,0),2)

    #ellipse = cv2.fitEllipse(cnt)
    #cv2.ellipse(img,ellipse,(0,255,0),2)


    #fit line\
    rows,cols = img.shape[:2]
    [vx,vy,x,y] = cv2.fitLine(cnt, cv2.DIST_L2,0,0.01,0.01)
    lefty = int((-x*vy/vx) + y)
    righty = int(((cols-x)*vy/vx)+y)
    cv2.line(img,(cols-1,righty),(0,lefty),(0,255,0),2)


#contour on the masked image\
    mask = np.zeros(img_gray.shape,np.uint8)
    cv2.drawContours(mask,[cnt],0,255, -1)
    print("\\ncontours object", [cnt])

#pixel points in a contour\
    pixelpoints1 = np.transpose(np.nonzero(mask))
    print ('\\npixelpoints  mask') 
    print (pixelpoints1)

cv2.imshow("line", img)
cv2.imshow("mask1", mask)


min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(img_gray,mask = mask)
print("\\nminMaxValLoc")
print("minVal =",min_val)
print("maxVal =", max_val)
print("MinLocation =", min_loc)
print("minLocation =", max_loc)

mean_val = cv2.mean(img,mask = mask)

print("\\nmean =", mean_val)

cv2.circle(img_gray, min_loc, 5, (0,122,0), 2)
cv2.circle(img_gray, max_loc, 5, (0,255,0), 2)
cv2.imshow("min_loc_max_loc_ImgGray", img_gray)

cv2.waitKey(0)
cv2.destroyAllWindows()


error: /Users/jenkins/miniconda/1/x64/conda-bld/conda_1486587097465/work/opencv-3.1.0/modules/imgproc/src/imgwarp.cpp:3229: error: (-215) ssize.area() > 0 in function resize


In [ ]:
from __future__ import print_function

import cv2
import numpy as np

img = np.zeros((256,256,3), np.uint8)

for i in range(22):
    img = cv2.line(img,(32,32+i),(96,32+i),(255, 255, 255),1)
    
for i in range(20):
    img = cv2.line(img,(32,54+i),(64,54+i),(255, 255, 255),1)

for i in range(22):
    img = cv2.line(img,(32,74+i),(96,74+i),(255, 255, 255),1)

iimg_blr0 = cv2.GaussianBlur(img, (3, 3), 2, 3) #5 by 5 kernel, sigma 3 for x and y\
img_blr1 = cv2.GaussianBlur(img, (5, 5), 3, 3) #5 by 5 kernel, sigma 3 for x and y\
img_blr2 = cv2.GaussianBlur(img, (7, 7), 3, 7) 
img_blr3 = cv2.GaussianBlur(img, (19, 19), 23, 31)
img_blr4 = cv2.GaussianBlur(img, (21,21), 36, 47)

#cv2.namedWindow('gaussian1',0)\
#cv2.resizeWindow('gaussian1',256,256)\
cv2.imshow('gaussian1',img_blr1)
cv2.imshow('gaussian2',img_blr2)
cv2.imshow('gaussian3',img_blr3)
cv2.imshow('gaussian4',img_blr4) 

#img_diff \
img_diff1 = img - img_blr1 
img_diff2 = img - img_blr2 
img_diff3 = img - img_blr3
img_diff4 = img - img_blr4

cv2.imshow('diff1', img_diff1) 
cv2.imshow('diff2', img_diff2)
cv2.imshow('diff3', img_diff3)
cv2.imshow('diff4', img_diff4)

#img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow('gray image', img_gray)

ret,thresh = cv2.threshold(img_gray,200,255,0) #threshold=220
cv2.imshow('thresholded binary',thresh)

_,contours,hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
contours = [cv2.approxPolyDP(cnt, 3, True) for cnt in contours]
print ('contours')
#print (contours)

epsilon = 0.001*cv2.arcLength(contours[0],True) 
approx = cv2.approxPolyDP(contours[0],epsilon,True) 

#hull = cv2.convexHull(cnt)
cv2.drawContours(img, contours, -1, (128,255,255),3) #draw contours on original image\
#1st argument: source image
#2nd argument: contours as a Python list\
#3rd argument: index of contours for individual contour. \
#4-5-6:        color,\
#7th argument: thickness.\

#cv2.drawContours(img, hull, -1, (0,0,255),3)\
cv2.imshow('findContours',img) 



# new code addition\


#ellipse = cv2.fitEllipse(cnt)\
#cv2.ellipse('EllipsCountours',img) \

mask = np.zeros(thresh.shape,np.uint8)
cv2.drawContours(mask,contours[0],0,255,-1)
pixelpoints = np.transpose(np.nonzero(mask))
print ('[cnt]')
print("number of contours =", len(contours))
print ("background =", contours[0])

cnt = contours[0]
M = cv2.moments(cnt)
print (M)

x,y,w,h = cv2.boundingRect(contours[0])
cv2.rectangle(img, (x,y), (x+w, y+h), (0,0,255), 2)



cv2.imshow("brect", img)

#minized rectangle\
Rect = cv2.minAreaRect(cnt)
box = cv2.boxPoints(Rect)
box = np.int0(box)
cv2.drawContours(img, [box], 0, (0,255,0), 2)

cv2.imshow("mArect", img)

#circle\
(x,y),radius = cv2.minEnclosingCircle(cnt)
center = (int(x),int(y))
radius = int(radius)
cv2.circle(img,center,radius,(0,255,0),2)

ellipse = cv2.fitEllipse(cnt)
cv2.ellipse(img,ellipse,(0,255,0),2)

cv2.imshow("circle", img)

#fit line\
rows,cols = img.shape[:2]
[vx,vy,x,y] = cv2.fitLine(cnt, cv2.DIST_L2,0,0.01,0.01)
lefty = int((-x*vy/vx) + y)
righty = int(((cols-x)*vy/vx)+y)
cv2.line(img,(cols-1,righty),(0,lefty),(0,255,0),2)

cv2.imshow("line", img)

#contour on the masked image\
mask = np.zeros(img_gray.shape,np.uint8)
cv2.drawContours(mask,[cnt],0,255, -1)
print("\\ncontours object", [cnt])

#pixel points in a contour\
pixelpoints1 = np.transpose(np.nonzero(mask))
print ('\\npixelpoints  mask') 
print (pixelpoints1)

cv2.imshow("mask1", mask)


min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(img_gray,mask = mask)
print("\\nminMaxValLoc")
print("minVal =",min_val)
print("maxVal =", max_val)
print("MinLocation =", min_loc)
print("minLocation =", max_loc)

mean_val = cv2.mean(img,mask = mask)

print("\\nmean =", mean_val)

cv2.circle(img_gray, min_loc, 5, (0,122,0), 2)
cv2.circle(img_gray, max_loc, 5, (0,255,0), 2)
cv2.imshow("min_loc_max_loc_ImgGray", img_gray)

cv2.waitKey(0)
cv2.destroyAllWindows()



contours
[cnt]
number of contours = 1
background = [[[32 32]]

 [[32 95]]

 [[96 95]]

 [[96 74]]

 [[64 73]]

 [[65 53]]

 [[96 53]]

 [[96 32]]]
{'mu03': -130094.8808760643, 'm11': 13098689.333333332, 'nu11': 0.00018486027620330203, 'nu12': 0.005573244017382632, 'm30': 972910093.8000001, 'nu21': -1.2834046981784338e-06, 'mu11': 2119.422327229753, 'm02': 14979900.666666666, 'mu12': 3718137.470973015, 'mu30': 5115236.444013834, 'nu30': 0.007667403675001079, 'm01': 215135.3333333333, 'm21': 868466407.5333333, 'nu02': 0.11433996730874371, 'm10': 206126.0, 'nu20': 0.09738915185525306, 'm00': 3386.0, 'mu21': -856.2114064693451, 'mu02': 1310907.2678348776, 'nu03': -0.0001950036872479839, 'm20': 13664684.333333332, 'm03': 1118225152.4, 'm12': 915903291.0666666, 'mu20': 1116566.236463869}
\ncontours object [array([[[32, 32]],

       [[32, 95]],

       [[96, 95]],

       [[96, 74]],

       [[64, 73]],

       [[65, 53]],

       [[96, 53]],

       [[96, 32]]], dtype=int32)]
\npixelpoints 

In [3]:
n = 12
inf = 2**16
a = [inf]*(n+1)
a[-1] = 0
for i in range(n,0,-1):
    j = 1
    while j*j <= i:
        a[i-j*j] = min(a[i]+1, a[i-j*j])
        
        j+=1
        
a

[3, 3, 2, 1, 2, 4, 3, 2, 1, 3, 2, 1, 0]

In [5]:
s = "aaa"
s[:2]+s[2:]

'aaa'

In [107]:
s = '1+4-(15+4-(10-4))'
#SMALL ERROR AFTER CLOSING BRACKETS

def calc(s, sm = 0, i = 0):
    
    if i == len(s):
        return sm
    
    if s[i] == '(':
        return calc(s,0,i+1)
        
    elif s[i].isdigit():
        if len(s)!=i+1:
            if i-1>0 and s[i-1]=='-':
                return calc(s,-int(s[i]),i+1)
            else:
                return calc(s,int(s[i]),i+1)
        else:
            return [int(s[i]),i]
        
    elif s[i] == '+':
        a = calc(s,0,i+1)
        if a[1]+1==len(s):
            return [sm+a[0], a[1]]
        else:
            return calc(s,sm+a[0],a[1]+1)

    elif s[i] == '-':
        a = calc(s,0,i+1)
        print(a, sm)
        
        if i+1 < len(s) and s[i+1].isdigit():    
            if a[1]+1==len(s):
                return [sm+a[0], a[1]]
            else:
                return calc(s,sm+a[0],a[1]+1)
        else:
            if a[1]+1==len(s):
                return [sm-a[0], a[1]]
            else:
                return calc(s,sm-a[0],a[1]+1)
        
    elif s[i] == ')':
        return [sm,i]
    
calc(s)

[-4, 15] 0
[-4, 16] 4
[21, 18] 4


[-16, 18]

In [7]:
k = 'a2'
k[0].isdigit()

False

In [72]:
ss = '-'
sig = 1 if ss=='+'else -1
sig

-1

In [91]:

ord('A')

65

In [92]:
-5//2

-3

In [93]:
-(-(-5)//2)

-2

In [117]:
#calci

s = '1+4-(15+4-(10-4))+8+15'

sign = 1
res = 0
num = 0
stack = []

for i in range(len(s)):
    if s[i] == '+' or s[i] == '-':
        res+=sign*num
        sign = -1 if s[i] == '-' else 1
        num = 0
    elif s[i].isdigit():
        num = num*10+int(s[i])
        #print(res)
    elif s[i] == '(':
        stack.append(res)
        stack.append(sign)
        sign = 1
        res = 0
    elif s[i] == ')':
        res += sign*num
        res *= stack.pop()
        res += stack.pop()
        num = 0

res+sign*num
                

15

In [118]:
#skyline partly working code. without scary edge cases


import heapq
a = [[2, 9 ,10], [3, 7 ,15], [5, 12, 12], [15, 20, 10], [19, 24, 8] ]
# a = [ [1,-2], [1,3],  [3,5], [3,-3]]
#
# a.sort(key = lambda x: (x[0], -1*x[2]))
# print(a)

dic = {a[0][1]: a[0][2]}

que = [a[0][1]]
heapq.heapify(que)
res = [[a[0][0],a[0][2]]]
for i in a[1:]:
    while que and i[0] > que[0]:
        r = heapq.heappop(que)
        mx = 0
        prev_mx = max(dic.values())

        del dic[r]

        if dic:
            mx = max(dic.values())

        if prev_mx != mx:
            res.append([r,mx])

    if dic:
        if i[2] > max(dic.values()):
            res.append([i[0],i[2]])

    else:
        res.append([i[0],i[2]])

    heapq.heappush(que, i[1])
    dic[i[1]] = i[2]

while que:
    r = heapq.heappop(que)
    mx = 0
    prev_mx = max(dic.values())

    del dic[r]

    if dic:
        mx = max(dic.values())

    if prev_mx != mx:
        res.append([r, mx])

#[2 10], [3 15], [7 12], [12 0], [15 10], [20 8], [24, 0]
print(res)

[[2, 10], [3, 15], [7, 12], [12, 0], [15, 10], [20, 8], [24, 0]]


In [125]:
s = [100, 4, 200, 1, 3, 2]
s = set(s)
for i,c in enumerate(s):
    print(i,c)

0 1
1 2
2 3
3 100
4 4
5 200
